name: Create Release

on:
  push:
    tags:
      - 'v*'
#  pull_request:
#    branches:
#      - "main"

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1.3
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
    - name: Restore Packages
      run: nuget restore GoogleSheetUploadTest.sln
    - name: Build solution
      run: msbuild GoogleSheetUploadTest.sln -property:Configuration=Release -property:platform="Any CPU"
    - name: Zip directory
      run: 7z a -r -tzip GoogleDriveTest.zip .\GoogleDriveTest\bin\Release\*
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Google Drive Uploader
    - name: Upload release assets
      id: upload-release-assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: GoogleDriveTest.zip
        asset_name: GoogleDriveTest.zip
        asset_content_type: application/zip
